### ISSUE TITLE
Environment Errors

### ISSUE THREAD

**Issue by swrosati** [Tropini-lab/PUPpy#3]
1.  When installing via git environment following the docs - hit this error:**

# Clone PUPpy GitHub directory
`git clone https://github.com/Tropini-lab/PUPpy.git`

# Change directory
`cd PUPpy`

**Create and set up conda environment:**
```~/PUPpy$  conda deactivate
~/PUPpy$ conda env create -f puppy_env.yml 
conda-forge/linux-64                                        Using cache
conda-forge/noarch                                          Using cache
bioconda/linux-64                                           Using cache
bioconda/noarch                                             Using cache
pkgs/r/linux-64                                               No change
pkgs/r/noarch                                                 No change
pkgs/main/noarch                                              No change
pkgs/main/linux-64                                            No change
hghezzi/linux-64                                              No change
hghezzi/noarch                                                No change


Looking for: ['aria2==1.23.0=0', 'aws-c-auth==0.7.8=hcd8a21d_2', 'aws-c-cal==0.6.9=had988b7_2', 'aws-c-common==0.9.10=h10d778d_0', 'aws-c-compression==0.2.17=hb45f1eb_7', 'aws-c-event-stream==0.3.2=hbc2660c_8', 'aws-c-http==0.7.14=h1fa4523_3', 'aws-c-io==0.13.36=h3728bb0_2', 'aws-c-mqtt==0.9.10=h2150435_2', 'aws-c-s3==0.4.4=h960c460_0', 'aws-c-sdkutils==0.1.13=hb45f1eb_0', 'aws-checksums==0.1.17=hb45f1eb_6', 'aws-crt-cpp==0.24.11=hc04ff71_2', 'aws-sdk-cpp==1.11.210=h7d17a91_4', 'biopython==1.81=py310hb372a2b_1', 'blas==1.0=openblas', 'bokeh==3.3.2=pyhd8ed1ab_0', 'brotli==1.1.0=h0dc2134_1', 'brotli-bin==1.1.0=h0dc2134_1', 'brotli-python==1.1.0=py310h9e9d8ca_1', 'bzip2==1.0.8=h1de35cc_0', 'c-ares==1.23.0=h10d778d_0', 'ca-certificates==2023.11.17=h8857fd0_0', 'certifi==2023.11.17=pyhd8ed1ab_0', 'click==8.1.7=unix_pyh707e725_0', 'cloudpickle==3.0.0=pyhd8ed1ab_0', 'contourpy==1.2.0=py310ha697434_0', 'cycler==0.12.1=pyhd8ed1ab_0', 'cytoolz==0.12.2=py310h6729b98_1', 'dask==2023.12.0=pyhd8ed1ab_0', 'dask-core==2023.12.0=pyhd8ed1ab_0', 'distributed==2023.12.0=pyhd8ed1ab_0', 'fonttools==4.46.0=py310hb372a2b_0', 'freetype==2.12.1=h60636b9_2', 'fsspec==2023.12.2=pyhca7485f_0', 'gawk==5.3.0=h2c496e9_0', 'gettext==0.21.1=h8a4c099_0', 'gflags==2.2.2=h0a44026_0', 'glog==0.6.0=h8ac2a54_0', 'gmp==6.3.0=h93d8f39_0', 'icu==73.2=hf5e326d_0', 'importlib-metadata==7.0.0=pyha770c72_0', 'importlib_metadata==7.0.0=hd8ed1ab_0', 'jinja2==3.1.2=pyhd8ed1ab_1', 'kiwisolver==1.4.5=py310h88cfcbd_1', 'krb5==1.21.2=hb884880_0', 'lcms2==2.15=ha53face_2', 'lerc==4.0.0=hb486fe8_0', 'libabseil==20230802.1=cxx17_h048a20a_0', 'libarrow==14.0.1=h7e6b3eb_9_cpu', 'libarrow-acero==14.0.1=hc222712_9_cpu', 'libarrow-dataset==14.0.1=hc222712_9_cpu', 'libarrow-flight==14.0.1=ha1803ca_9_cpu', 'libarrow-flight-sql==14.0.1=h8ec153b_9_cpu', 'libarrow-gandiva==14.0.1=heeebe7c_9_cpu', 'libarrow-substrait==14.0.1=h8ec153b_9_cpu', 'libbrotlicommon==1.1.0=h0dc2134_1', 'libbrotlidec==1.1.0=h0dc2134_1', 'libbrotlienc==1.1.0=h0dc2134_1', 'libcrc32c==1.1.2=he9d5cce_0', 'libcurl==8.5.0=h726d00d_0', 'libcxx==16.0.6=hd57cbcb_0', 'libdeflate==1.19=ha4e1b8e_0', 'libedit==3.1.20221030=h6c40b1e_0', 'libev==4.33=h9ed2024_1', 'libevent==2.1.12=h04015c4_1', 'libffi==3.4.4=hecd8cb5_0', 'libgfortran==5.0.0=11_3_0_hecd8cb5_28', 'libgfortran5==11.3.0=h9dfd629_28', 'libgoogle-cloud==2.12.0=hc0857f6_4', 'libgrpc==1.59.3=ha7f534c_0', 'libiconv==1.17=hd75f5a5_1', 'libidn2==2.3.4=hb7f2c08_0', 'libjpeg-turbo==2.1.5.1=h0dc2134_1', 'libllvm15==15.0.7=hbedff68_4', 'libnghttp2==1.58.0=h64cf6d3_1', 'libopenblas==0.3.21=h54e7dc3_0', 'libparquet==14.0.1=h27bd29f_9_cpu', 'libpng==1.6.39=ha978bb4_0', 'libprotobuf==4.24.4=h0ee05dc_0', 'libre2-11==2023.06.02=h4694dbf_0', 'libsqlite==3.44.2=h92b6c6a_0', 'libssh2==1.11.0=hd019ec5_0', 'libthrift==0.19.0=h064b379_1', 'libtiff==4.6.0=haeeb97c_1', 'libunistring==0.9.10=h0d85af4_0', 'libutf8proc==2.8.0=hb7f2c08_0', 'libwebp-base==1.3.2=h0dc2134_0', 'libxcb==1.15=hb7f2c08_0', 'libxml2==2.12.3=hc0ae0f7_0', 'libzlib==1.2.13=h8a1eda9_5', 'llvm-openmp==17.0.6=hb6ac08f_0', 'locket==1.0.0=pyhd8ed1ab_0', 'lz4==4.3.2=py310h4c8952d_1', 'lz4-c==1.9.4=hcec6c5f_0', 'markupsafe==2.1.3=py310h6729b98_1', 'matplotlib==3.8.2=py310h2ec42d9_0', 'matplotlib-base==3.8.2=py310hec49e92_0', 'mmseqs2==15.6f452=pl5321hf590d3d_0', 'mpfr==4.2.1=h0c69b56_0', 'msgpack-python==1.0.7=py310ha697434_0', 'munkres==1.0.7=py_1', 'ncurses==6.4=hcec6c5f_0', 'numpy==1.26.2=py310hf6dca73_0', 'numpy-base==1.26.2=py310hd8f4981_0', 'openjpeg==2.5.0=ha4da562_3', 'openssl==3.2.0=hd75f5a5_1', 'orc==1.9.2=h9ab30d4_0', 'packaging==23.2=pyhd8ed1ab_0', 'pandas==1.5.3=py310hecf8f37_1', 'partd==1.4.1=pyhd8ed1ab_0', 'perl==5.32.1=4_h0dc2134_perl5', 'pillow==10.0.1=py310h5e9aaff_1', 'pip==23.3.1=py310hecd8cb5_0', 'psutil==5.9.5=py310h6729b98_1', 'pthread-stubs==0.4=hc929b4f_1001', 'pyarrow==14.0.1=py310hb3c8376_9_cpu', 'pyarrow-hotfix==0.6=pyhd8ed1ab_0', 'pyparsing==3.1.1=pyhd8ed1ab_0', 'pysocks==1.7.1=pyha2e5f31_6', 'python==3.10.6=hc14f532_0_cpython', 'python-dateutil==2.8.2=pyhd8ed1ab_0', 'python_abi==3.10=4_cp310', 'pytz==2023.3.post1=pyhd8ed1ab_0', 'pyyaml==6.0.1=py310h6729b98_1', 're2==2023.06.02=hd34609a_0', 'readline==8.2=hca72f7f_0', 'setuptools==68.2.2=py310hecd8cb5_0', 'six==1.16.0=pyh6c4a22f_0', 'snappy==1.1.10=h225ccf5_0', 'sortedcontainers==2.4.0=pyhd8ed1ab_0', 'sqlite==3.44.2=h7461747_0', 'tblib==3.0.0=pyhd8ed1ab_0', 'tk==8.6.12=h5d9f67b_0', 'toolz==0.12.0=pyhd8ed1ab_0', 'tornado==6.3.3=py310h6729b98_1', 'tzdata==2023c=h04d1e81_0', 'unicodedata2==15.1.0=py310h6729b98_0', 'urllib3==2.1.0=pyhd8ed1ab_0', 'wget==1.20.3=hd3787cc_1', 'wheel==0.41.2=py310hecd8cb5_0', 'xorg-libxau==1.0.11=h0dc2134_0', 'xorg-libxdmcp==1.1.3=h35c211d_0', 'xyzservices==2023.10.1=pyhd8ed1ab_0', 'xz==5.4.5=h6c40b1e_0', 'yaml==0.2.5=h0d85af4_2', 'zict==3.0.0=pyhd8ed1ab_0', 'zipp==3.17.0=pyhd8ed1ab_0', 'zlib==1.2.13=h8a1eda9_5', 'zstd==1.5.5=hc035e20_0']


Could not solve for environment specs
Encountered problems while solving:
  - nothing provides requested aws-c-auth ==0.7.8 hcd8a21d_2
  - nothing provides requested aws-c-cal ==0.6.9 had988b7_2
  - nothing provides requested aws-c-common ==0.9.10 h10d778d_0
  - nothing provides requested aws-c-compression ==0.2.17 hb45f1eb_7
  - nothing provides requested aws-c-event-stream ==0.3.2 hbc2660c_8
  - nothing provides requested aws-c-http ==0.7.14 h1fa4523_3
  - nothing provides requested aws-c-io ==0.13.36 h3728bb0_2
  - nothing provides requested aws-c-mqtt ==0.9.10 h2150435_2
  - nothing provides requested aws-c-s3 ==0.4.4 h960c460_0
  - nothing provides requested aws-c-sdkutils ==0.1.13 hb45f1eb_0
  - nothing provides requested aws-checksums ==0.1.17 hb45f1eb_6
  - nothing provides requested aws-crt-cpp ==0.24.11 hc04ff71_2
  - nothing provides requested aws-sdk-cpp ==1.11.210 h7d17a91_4
  - nothing provides requested biopython ==1.81 py310hb372a2b_1
  - nothing provides requested brotli ==1.1.0 h0dc2134_1
  - nothing provides requested brotli-bin ==1.1.0 h0dc2134_1
  - nothing provides requested brotli-python ==1.1.0 py310h9e9d8ca_1
  - nothing provides requested bzip2 ==1.0.8 h1de35cc_0
  - nothing provides requested c-ares ==1.23.0 h10d778d_0
  - nothing provides requested ca-certificates ==2023.11.17 h8857fd0_0
  - nothing provides requested contourpy ==1.2.0 py310ha697434_0
  - nothing provides requested cytoolz ==0.12.2 py310h6729b98_1
  - nothing provides requested fonttools ==4.46.0 py310hb372a2b_0
  - nothing provides requested freetype ==2.12.1 h60636b9_2
  - nothing provides requested gawk ==5.3.0 h2c496e9_0
  - nothing provides requested gettext ==0.21.1 h8a4c099_0
  - nothing provides requested gflags ==2.2.2 h0a44026_0
  - nothing provides requested glog ==0.6.0 h8ac2a54_0
  - nothing provides requested gmp ==6.3.0 h93d8f39_0
  - nothing provides requested icu ==73.2 hf5e326d_0
  - nothing provides requested kiwisolver ==1.4.5 py310h88cfcbd_1
  - nothing provides requested krb5 ==1.21.2 hb884880_0
  - nothing provides requested lcms2 ==2.15 ha53face_2
  - nothing provides requested lerc ==4.0.0 hb486fe8_0
  - nothing provides requested libabseil ==20230802.1 cxx17_h048a20a_0
  - nothing provides requested libarrow ==14.0.1 h7e6b3eb_9_cpu
  - nothing provides requested libarrow-acero ==14.0.1 hc222712_9_cpu
  - nothing provides requested libarrow-dataset ==14.0.1 hc222712_9_cpu
  - nothing provides requested libarrow-flight ==14.0.1 ha1803ca_9_cpu
  - nothing provides requested libarrow-flight-sql ==14.0.1 h8ec153b_9_cpu
  - nothing provides requested libarrow-gandiva ==14.0.1 heeebe7c_9_cpu
  - nothing provides requested libarrow-substrait ==14.0.1 h8ec153b_9_cpu
  - nothing provides requested libbrotlicommon ==1.1.0 h0dc2134_1
  - nothing provides requested libbrotlidec ==1.1.0 h0dc2134_1
  - nothing provides requested libbrotlienc ==1.1.0 h0dc2134_1
  - nothing provides requested libcrc32c ==1.1.2 he9d5cce_0
  - nothing provides requested libcurl ==8.5.0 h726d00d_0
  - nothing provides requested libcxx ==16.0.6 hd57cbcb_0
  - nothing provides requested libdeflate ==1.19 ha4e1b8e_0
  - nothing provides requested libedit ==3.1.20221030 h6c40b1e_0
  - nothing provides requested libev ==4.33 h9ed2024_1
  - nothing provides requested libevent ==2.1.12 h04015c4_1
  - nothing provides requested libffi ==3.4.4 hecd8cb5_0
  - nothing provides requested libgfortran ==5.0.0 11_3_0_hecd8cb5_28
  - nothing provides requested libgfortran5 ==11.3.0 h9dfd629_28
  - nothing provides requested libgoogle-cloud ==2.12.0 hc0857f6_4
  - nothing provides requested libgrpc ==1.59.3 ha7f534c_0
  - nothing provides requested libiconv ==1.17 hd75f5a5_1
  - nothing provides requested libidn2 ==2.3.4 hb7f2c08_0
  - nothing provides requested libjpeg-turbo ==2.1.5.1 h0dc2134_1
  - nothing provides requested libllvm15 ==15.0.7 hbedff68_4
  - nothing provides requested libnghttp2 ==1.58.0 h64cf6d3_1
  - nothing provides requested libopenblas ==0.3.21 h54e7dc3_0
  - nothing provides requested libparquet ==14.0.1 h27bd29f_9_cpu
  - nothing provides requested libpng ==1.6.39 ha978bb4_0
  - nothing provides requested libprotobuf ==4.24.4 h0ee05dc_0
  - nothing provides requested libre2-11 ==2023.06.02 h4694dbf_0
  - nothing provides requested libsqlite ==3.44.2 h92b6c6a_0
  - nothing provides requested libssh2 ==1.11.0 hd019ec5_0
  - nothing provides requested libthrift ==0.19.0 h064b379_1
  - nothing provides requested libtiff ==4.6.0 haeeb97c_1
  - nothing provides requested libunistring ==0.9.10 h0d85af4_0
  - nothing provides requested libutf8proc ==2.8.0 hb7f2c08_0
  - nothing provides requested libwebp-base ==1.3.2 h0dc2134_0
  - nothing provides requested libxcb ==1.15 hb7f2c08_0
  - nothing provides requested libxml2 ==2.12.3 hc0ae0f7_0
  - nothing provides requested libzlib ==1.2.13 h8a1eda9_5
  - nothing provides requested llvm-openmp ==17.0.6 hb6ac08f_0
  - nothing provides requested lz4 ==4.3.2 py310h4c8952d_1
  - nothing provides requested lz4-c ==1.9.4 hcec6c5f_0
  - nothing provides requested markupsafe ==2.1.3 py310h6729b98_1
  - nothing provides requested matplotlib ==3.8.2 py310h2ec42d9_0
  - nothing provides requested matplotlib-base ==3.8.2 py310hec49e92_0
  - nothing provides requested mmseqs2 ==15.6f452 pl5321hf590d3d_0
  - nothing provides requested mpfr ==4.2.1 h0c69b56_0
  - nothing provides requested msgpack-python ==1.0.7 py310ha697434_0
  - nothing provides requested ncurses ==6.4 hcec6c5f_0
  - nothing provides requested numpy ==1.26.2 py310hf6dca73_0
  - nothing provides requested numpy-base ==1.26.2 py310hd8f4981_0
  - nothing provides requested openjpeg ==2.5.0 ha4da562_3
  - nothing provides requested openssl ==3.2.0 hd75f5a5_1
  - nothing provides requested orc ==1.9.2 h9ab30d4_0
  - nothing provides requested pandas ==1.5.3 py310hecf8f37_1
  - nothing provides requested perl ==5.32.1 4_h0dc2134_perl5
  - nothing provides requested pillow ==10.0.1 py310h5e9aaff_1
  - nothing provides requested pip ==23.3.1 py310hecd8cb5_0
  - nothing provides requested psutil ==5.9.5 py310h6729b98_1
  - nothing provides requested pthread-stubs ==0.4 hc929b4f_1001
  - nothing provides requested pyarrow ==14.0.1 py310hb3c8376_9_cpu
  - nothing provides requested python ==3.10.6 hc14f532_0_cpython
  - nothing provides requested pyyaml ==6.0.1 py310h6729b98_1
  - nothing provides requested re2 ==2023.06.02 hd34609a_0
  - nothing provides requested readline ==8.2 hca72f7f_0
  - nothing provides requested setuptools ==68.2.2 py310hecd8cb5_0
  - nothing provides requested snappy ==1.1.10 h225ccf5_0
  - nothing provides requested sqlite ==3.44.2 h7461747_0
  - nothing provides requested tk ==8.6.12 h5d9f67b_0
  - nothing provides requested tornado ==6.3.3 py310h6729b98_1
  - nothing provides requested unicodedata2 ==15.1.0 py310h6729b98_0
  - nothing provides requested wget ==1.20.3 hd3787cc_1
  - nothing provides requested wheel ==0.41.2 py310hecd8cb5_0
  - nothing provides requested xorg-libxau ==1.0.11 h0dc2134_0
  - nothing provides requested xorg-libxdmcp ==1.1.3 h35c211d_0
  - nothing provides requested xz ==5.4.5 h6c40b1e_0
  - nothing provides requested yaml ==0.2.5 h0d85af4_2
  - nothing provides requested zlib ==1.2.13 h8a1eda9_5
  - nothing provides requested zstd ==1.5.5 hc035e20_0

The environment can't be solved, aborting the operation
```

2. When installing via conda, I'm able to install, but hit what appears to be a Numpy version issue when running puppy-align:

```(puppy) ubuntu$ puppy-align -pr puppy/data/small-test/intended -nt puppy/data/small-test/unintended -o puppy/data/small-test/alignment_output

                                                                                
                 @    @ @ @                  @     @                            
              @       @                      @       @                          
           @         @                         @       @                        
        @          @                             @       @                      
     @            @                               @         @                   
   @            @                                  @           @                
 @             @                                                 @              
@             @       @@@@@@             @@@@@@     @             ,             
             @        @@@@@@@           @@@@@@@     @                           
 @           @        @@@@@@   @@@@@@@    @@@@                   @              
   @         @          @@     @@@@@@      @                   @                
     @        @        @          @          @      @        @  @   @  @   @    
        @      @      @                       @     @      @    @      @@  @@   
             @@@                               @   @   @        @   @@  @     @@
      @@@@@@        @               @@@@@       @       @  @@   @@    @  @    @ 
      @@@@@@@@@                @@@@@@@@         @@@@/    ( @ @@@ @   @  @       
        @@@@@@@@@@@@          @@@@@@@@@         @@@@@    @ @ @   @   @@  @      
       @@@@@@@@              @        @        @       @ @ @@    @  @           
       @@@@@@          @@ @@          (@ @@@@                 

ASCII art designed with manytools.org from puppy logo                  

Traceback (most recent call last):
  File "/home/ubuntu/mambaforge/envs/puppy-conda/bin/puppy-align", line 92, in <module>
    import pandas as pd
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pandas/__init__.py", line 11, in <module>
    __import__(_dependency)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/numpy/__init__.py", line 144, in <module>
    from . import lib
  File "/home/ubuntu/.local/lib/python3.10/site-packages/numpy/lib/__init__.py", line 73, in <module>
    __all__ += npyio.__all__
AttributeError: module 'numpy.lib.npyio' has no attribute '__all__'. Did you mean: '__file__'? ```

**Comment by hghezzi** [comment]
Hi!

I am not immediately sure what the problem could be, so I could use a little extra information. 

What conda version are you using? I had a similar issue where none of the packages could be found which disappeared after updating conda.

Which architecture are you using? `uname -m` to find out

Do you have the stdout for the puppy conda installation? Did everything work smoothly? Could you also show which puppy-align command you ran?

**Comment by Wednesdaysama** [comment]
Hi, I faced the same problem. I had an ancient Conda (version 4). Now I have updated it to version 24, and the environment problem is fixed. Hope this could help you.
