### ISSUE TITLE
Issues running align command- Errors regarding input files

### ISSUE THREAD

**Issue by cvtang** [Tropini-lab/PUPpy#7]
Thank you for developing this tool! 
I am trying to develop species specific primers for a 15 member bacterial community. I installed PUPpy using the conda installation.  The input files I used were produced using PROKKA and the extension files were renamed as required. I proceeded to run puppy-align and obtained the error below. I am not sure if this is related to my input files or MMseqs2 or maybe a problem with the conda environment. I am relatively new to bioinformatics so I apologize in advance for any missing information. I tried to search for this error in forums but did not find a suitable answer to go on. Could you help?

Code used and error
```
$ puppy-align --pr 1.Target -nt 2.NoTarget


                 @    @ @ @                  @     @
              @       @                      @       @
           @         @                         @       @
        @          @                             @       @
     @            @                               @         @
   @            @                                  @           @
 @             @                                                 @
@             @       @@@@@@             @@@@@@     @             
             @        @@@@@@@           @@@@@@@     @
 @           @        @@@@@@   @@@@@@@    @@@@                   @
   @         @          @@     @@@@@@      @                   @
     @        @        @          @          @      @        @  @   @  @   @
        @      @      @                       @     @      @    @      @@  @@
             @@@                               @   @   @        @   @@  @     @@
      @@@@@@        @               @@@@@       @       @  @@   @@    @  @    @
      @@@@@@@@@                @@@@@@@@         @@@@/    ( @ @@@ @   @  @
        @@@@@@@@@@@@          @@@@@@@@@         @@@@@    @ @ @   @   @@  @
       @@@@@@@@              @        @        @       @ @ @@    @  @
       @@@@@@          @@ @@          (@ @@@@

ASCII art designed with manytools.org from puppy logo

2024-01-11 15:10:01,981 - INFO - Renaming FASTA headers of input CDS files
2024-01-11 15:10:01,981 - INFO - Aligning genes with MMseqs2. This might take a while.
createdb /Puppy/Align_OUT/concatenated_CDSes.fna /Puppy/Align_OUT/QueryDB

MMseqs Version:         15.6f452
Database type           0
Shuffle input database  true
Createdb mode           0
Write lookup file       1
Offset of numeric ids   0
Compressed              0
Verbosity               3

Converting sequences
File concatenated_CDSes.fna is empty or invalid and was ignored

Time for merging to QueryDB_h: 0h 0m 0s 228ms
Time for merging to QueryDB: 0h 0m 0s 8ms
Database type: Nucleotide
The input files have no entry:  - /Puppy/Align_OUT/concatenated_CDSes.fna
Please check your input files. Only files in fasta/fastq[.gz|bz2] are supported
Traceback (most recent call last):
  File "/tools/miniconda3/envs/puppy/lib/python3.10/shutil.py", line 816, in move
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: '/Puppy/Align_OUT/tmp' -> `'/Puppy/Align_OUT/mmseqs_tmp'`

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tools/miniconda3/envs/puppy/bin/puppy-align", line 290, in <module>
    success = run_mmseqs2(output, cds_intended, cds_unintended, args.identity)
  File "/tools/miniconda3/envs/puppy/bin/puppy-align", line 235, in run_mmseqs2
    shutil.move(f"{output}/tmp", f"{output}/mmseqs_tmp")
  File "/tools/miniconda3/envs/puppy/lib/python3.10/shutil.py", line 836, in move
    copy_function(src, real_dst)
  File "/tools/miniconda3/envs/puppy/lib/python3.10/shutil.py", line 434, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/tools/miniconda3/envs/puppy/lib/python3.10/shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/Puppy/Align_OUT/tmp'
```

Sample fasta lines of input files:

>CBEJKNKA_00001 23S ribosomal RNA
TTAAGCGACTAAGCGTACACGGTGGATGCCCTGGCAGTCAGAGGCGATGAAGGACGTGCT
AATCTGCGAAAAGCGCCGGTAAGGTGATATGAACCGTTATAACCGGCGATGTCCGAATGG
GGAAACCCAGTGCAATCCGTTGCACTATCACAGCATGAATACATAGTGCTGTGAGGCGAA
CCGGGGGAACTGAAACATCTAAGTACCCCGAGGAAAAGAAATCAACCGAGATTCCCCCAG
TAGCGGCGAGCGAACGGGGAACAGCCCAGAGCCTGAATCAGCCTGAGTGTTAGTGGAAGC
GTCTGGAAAGTCGCGCGATACAGGGTGACAGCCCCGTACACAAAAGCACTCTTGCTGTGA

**Comment by hghezzi** [comment]
Hi!

Thank you for providing details about the error and code. If you look at the message immediately after "Converting sequences" you will see this message: "File concatenated_CDSes.fna is empty or invalid and was ignored". This is the first problem that causes the rest to break down and it is usually related to issues with the input files. 

The sample fasta line you provided looks correct. Did you provide the correct file paths for your input folders? Did you check that the filenames meet all the requirements listed under "INPUT" in the documentation? 

ps. a small detail, the flag "pr" should be written with a single dash not two (-pr, not --pr). My apologies!

**Comment by cvtang** [comment]
Thank you for your prompt response! 
As suggested I checked the input files to make sure I didn't miss anything. One thing I noticed was that I did not add the 'cds' string properly: I added '.cds' and it seems like the program is looking for '_cds'. I totally missed that.

I went ahead and changed that and re-ran the command and I have now a new issue...

```
puppy-align -pr /Puppy/1.Target -nt /Puppy/2.NoTarget -o 3.Test1/


                 @    @ @ @                  @     @
              @       @                      @       @
           @         @                         @       @
        @          @                             @       @
     @            @                               @         @
   @            @                                  @           @
 @             @                                                 @
@             @       @@@@@@             @@@@@@     @             ,
             @        @@@@@@@           @@@@@@@     @
 @           @        @@@@@@   @@@@@@@    @@@@                   @
   @         @          @@     @@@@@@      @                   @
     @        @        @          @          @      @        @  @   @  @   @
        @      @      @                       @     @      @    @      @@  @@
             @@@                               @   @   @        @   @@  @     @@
      @@@@@@        @               @@@@@       @       @  @@   @@    @  @    @
      @@@@@@@@@                @@@@@@@@         @@@@/    ( @ @@@ @   @  @
        @@@@@@@@@@@@          @@@@@@@@@         @@@@@    @ @ @   @   @@  @
       @@@@@@@@              @        @        @       @ @ @@    @  @
       @@@@@@          @@ @@          (@ @@@@

ASCII art designed with manytools.org from puppy logo

2024-01-12 08:33:16,678 - INFO - Renaming FASTA headers of input CDS files
Traceback (most recent call last):
  File "/tools/miniconda3/envs/puppy/bin/puppy-align", line 282, in <module>
    rename_fasta(f, name[:i])
  File "/tools/miniconda3/envs/puppy/bin/puppy-align", line 167, in rename_fasta
    new_lines = rename_fasta_headers(data, species_name)
  File "/tools/miniconda3/envs/puppy/bin/puppy-align", line 181, in rename_fasta_headers
    new_lines.append(change_header(line, species_name))
  File "/tools/miniconda3/envs/puppy/bin/puppy-align", line 205, in change_header
    new_line = f">lcl|{name}-{parts[1]}"
IndexError: list index out of range
```

Here is what my input file names look like:
c104.contigs_cds.fna  c128.contigs_cds.fna    c1_polish_cds.fna      c3.contigs_cds.fna    c55.contigs_cds.fna   c83_polish_cds.fna
c10_polished_cds.fna  c130_polished_cds.fna   c20_polish_cds.fna     c42.contigs_cds.fna   c56.contigs_cds.fna   c85.contigs_cds.fna
c111_polish_cds.fna   c131.contigs_cds.fna    c21_polish_cds.fna     c43_polished_cds.fna  c59_polish_cds.fna    c89_polished_cds.fna
c112_polish_cds.fna   c134_polish_cds.fna     c22_polished_cds.fna   c44_polished_cds.fna  c5_polish_cds.fna     c90_polish_cds.fna

could there be another issue with the input files or something else?

**Comment by hghezzi** [comment]
Although I don't think this is the problem, I generally tend to avoid using dots (".") in the middle of filenames and only use them for the extensions (i.e. c104_contigs_cds.fna not c104.contigs_cds.fna).

One thing I have just noticed is that the sample FASTA header you copied in the first message is missing the initial ">" sign. I am not sure if it's just a copy-paste typo, but all FASTA headers must start with >. 

Let me know if anything changes or new errors come up, and thank you for the patience!

**Comment by cvtang** [comment]
Thank YOU for your patience!  ;) 
I thought about that and substituted the mid "." by "_" but that got me to the same result.
The lack of '>' at the beginning is a copy paste feat. My files have a '>' at the beginning of each header. 

I do not know if this could help but here is a list of software in my conda environment.. maybe something went wrong with the installation and there is an issue with versions? (my conda version is 22.9.0)

Thanks again!

```
# packages in environment at /tools/miniconda3/envs/puppy:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
aria2                     1.37.0               h347180d_1    conda-forge
aws-c-auth                0.7.11               h0100c56_0    conda-forge
aws-c-cal                 0.6.9                h5d48c4d_2    conda-forge
aws-c-common              0.9.10               hd590300_0    conda-forge
aws-c-compression         0.2.17               h7f92143_7    conda-forge
aws-c-event-stream        0.4.1                h0bcb0bb_1    conda-forge
aws-c-http                0.8.0                hd268abd_1    conda-forge
aws-c-io                  0.13.36              hb3b01f7_3    conda-forge
aws-c-mqtt                0.10.0               hf5d392a_2    conda-forge
aws-c-s3                  0.4.7                hf8c57b3_3    conda-forge
aws-c-sdkutils            0.1.13               h7f92143_0    conda-forge
aws-checksums             0.1.17               h7f92143_6    conda-forge
aws-crt-cpp               0.26.0               h600aa22_5    conda-forge
aws-sdk-cpp               1.11.210             h405b101_9    conda-forge
biopython                 1.83            py310h2372a71_0    conda-forge
bokeh                     3.3.3              pyhd8ed1ab_0    conda-forge
brotli                    1.1.0                hd590300_1    conda-forge
brotli-bin                1.1.0                hd590300_1    conda-forge
brotli-python             1.1.0           py310hc6cd4ac_1    conda-forge
bzip2                     1.0.8                hd590300_5    conda-forge
c-ares                    1.25.0               hd590300_0    conda-forge
ca-certificates           2023.11.17           hbcca054_0    conda-forge
certifi                   2023.11.17         pyhd8ed1ab_0    conda-forge
click                     8.1.7           unix_pyh707e725_0    conda-forge
cloudpickle               3.0.0              pyhd8ed1ab_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
contourpy                 1.2.0           py310hd41b1e2_0    conda-forge
cycler                    0.12.1             pyhd8ed1ab_0    conda-forge
cyrus-sasl                2.1.28               h52b45da_1
cytoolz                   0.12.2          py310h2372a71_1    conda-forge
dask                      2023.12.1          pyhd8ed1ab_0    conda-forge
dask-core                 2023.12.1          pyhd8ed1ab_0    conda-forge
dbus                      1.13.18              hb2f20db_0
distributed               2023.12.1          pyhd8ed1ab_0    conda-forge
expat                     2.5.0                hcb278e6_1    conda-forge
fontconfig                2.14.2               h14ed4e7_0    conda-forge
fonttools                 4.47.0          py310h2372a71_0    conda-forge
freetype                  2.12.1               h267a509_2    conda-forge
fsspec                    2023.12.2          pyhca7485f_0    conda-forge
gawk                      5.3.0                ha916aea_0    conda-forge
gettext                   0.21.1               h27087fc_0    conda-forge
gflags                    2.2.2             he1b5a44_1004    conda-forge
giflib                    5.2.1                h0b41bf4_3    conda-forge
glib                      2.78.3               hfc55251_0    conda-forge
glib-tools                2.78.3               hfc55251_0    conda-forge
glog                      0.6.0                h6f12383_0    conda-forge
gmp                       6.3.0                h59595ed_0    conda-forge
gst-plugins-base          1.14.1               h6a678d5_1
gstreamer                 1.14.1               h5eee18b_1
icu                       73.2                 h59595ed_0    conda-forge
importlib-metadata        7.0.1              pyha770c72_0    conda-forge
importlib_metadata        7.0.1                hd8ed1ab_0    conda-forge
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
jpeg                      9e                   h0b41bf4_3    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.4.5           py310hd41b1e2_1    conda-forge
krb5                      1.20.1               h81ceb04_0    conda-forge
lcms2                     2.12                 h3be6417_0
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
lerc                      3.0                  h295c915_0
libabseil                 20230802.1      cxx17_h59595ed_0    conda-forge
libarrow                  14.0.2           h84dd17c_2_cpu    conda-forge
libarrow-acero            14.0.2           h59595ed_2_cpu    conda-forge
libarrow-dataset          14.0.2           h59595ed_2_cpu    conda-forge
libarrow-flight           14.0.2           h120cb0d_2_cpu    conda-forge
libarrow-flight-sql       14.0.2           h61ff412_2_cpu    conda-forge
libarrow-gandiva          14.0.2           hacb8726_2_cpu    conda-forge
libarrow-substrait        14.0.2           h61ff412_2_cpu    conda-forge
libblas                   3.9.0           20_linux64_openblas    conda-forge
libbrotlicommon           1.1.0                hd590300_1    conda-forge
libbrotlidec              1.1.0                hd590300_1    conda-forge
libbrotlienc              1.1.0                hd590300_1    conda-forge
libcblas                  3.9.0           20_linux64_openblas    conda-forge
libclang                  14.0.6          default_hc6dbbc7_1
libclang13                14.0.6          default_he11475f_1
libcrc32c                 1.1.2                h9c3ff4c_0    conda-forge
libcups                   2.3.3                h36d4200_3    conda-forge
libcurl                   8.5.0                h251f7ec_0
libdeflate                1.17                 h5eee18b_1
libedit                   3.1.20230828         h5eee18b_0
libev                     4.33                 hd590300_2    conda-forge
libevent                  2.1.12               hf998b51_1    conda-forge
libexpat                  2.5.0                hcb278e6_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 13.2.0               h807b86a_3    conda-forge
libgfortran-ng            13.2.0               h69a702a_3    conda-forge
libgfortran5              13.2.0               ha4646dd_3    conda-forge
libglib                   2.78.3               h783c2da_0    conda-forge
libgomp                   13.2.0               h807b86a_3    conda-forge
libgoogle-cloud           2.12.0               h5206363_4    conda-forge
libgrpc                   1.59.3               hd6c4280_0    conda-forge
libiconv                  1.17                 hd590300_2    conda-forge
libidn2                   2.3.4                h166bdaf_0    conda-forge
liblapack                 3.9.0           20_linux64_openblas    conda-forge
libllvm14                 14.0.6               hcd5def8_4    conda-forge
libllvm15                 15.0.7               hb3ce162_4    conda-forge
libnghttp2                1.58.0               h47da74e_1    conda-forge
libnl                     3.9.0                hd590300_0    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libnuma                   2.0.16               h0b41bf4_1    conda-forge
libopenblas               0.3.25          pthreads_h413a1c8_0    conda-forge
libparquet                14.0.2           h352af49_2_cpu    conda-forge
libpng                    1.6.39               h753d276_0    conda-forge
libpq                     12.15                hdbd6064_1
libprotobuf               4.24.4               hf27288f_0    conda-forge
libre2-11                 2023.06.02           h7a70373_0    conda-forge
libsqlite                 3.44.2               h2797004_0    conda-forge
libssh2                   1.11.0               h0841786_0    conda-forge
libstdcxx-ng              13.2.0               h7e041cc_3    conda-forge
libthrift                 0.19.0               hb90f79a_1    conda-forge
libtiff                   4.5.1                h6a678d5_0
libunistring              0.9.10               h7f98852_0    conda-forge
libutf8proc               2.8.0                h166bdaf_0    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libwebp                   1.3.2                h11a3e52_0
libwebp-base              1.3.2                hd590300_0    conda-forge
libxcb                    1.15                 h0b41bf4_0    conda-forge
libxcrypt                 4.4.36               hd590300_1    conda-forge
libxkbcommon              1.6.0                hd429924_1    conda-forge
libxml2                   2.12.3               h232c23b_0    conda-forge
libzlib                   1.2.13               hd590300_5    conda-forge
locket                    1.0.0              pyhd8ed1ab_0    conda-forge
lz4                       4.3.3           py310h350c4a5_0    conda-forge
lz4-c                     1.9.4                hcb278e6_0    conda-forge
markupsafe                2.1.3           py310h2372a71_1    conda-forge
matplotlib                3.8.2           py310hff52083_0    conda-forge
matplotlib-base           3.8.2           py310h62c0568_0    conda-forge
mmseqs2                   15.6f452        pl5321h6a68c12_0    bioconda
mpfr                      4.2.1                h9458935_0    conda-forge
msgpack-python            1.0.7           py310hd41b1e2_0    conda-forge
munkres                   1.0.7                      py_1    bioconda
mysql                     5.7.24               h721c034_2
ncurses                   6.4                  h59595ed_2    conda-forge
numpy                     1.26.3          py310hb13e2d6_0    conda-forge
openjpeg                  2.5.0                hfec8fc6_2    conda-forge
openssl                   3.2.0                hd590300_1    conda-forge
orc                       1.9.2                h4b38347_0    conda-forge
packaging                 23.2               pyhd8ed1ab_0    conda-forge
pandas                    2.1.4           py310hcc13569_0    conda-forge
partd                     1.4.1              pyhd8ed1ab_0    conda-forge
patsy                     0.5.6              pyhd8ed1ab_0    conda-forge
pcre2                     10.42                hcad00b1_0    conda-forge
perl                      5.32.1          7_hd590300_perl5    conda-forge
pillow                    10.0.1          py310ha6cbd5a_0
pip                       23.3.2             pyhd8ed1ab_0    conda-forge
ply                       3.11                       py_1    conda-forge
primer3-py                2.0.1           py310h4b81fae_1    bioconda
psutil                    5.9.7           py310h2372a71_0    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
puppy                     1.0.1                   py310_0    hghezzi
pyarrow                   14.0.2          py310hf9e7431_2_cpu    conda-forge
pyarrow-hotfix            0.6                pyhd8ed1ab_0    conda-forge
pyparsing                 3.1.1              pyhd8ed1ab_0    conda-forge
pyqt                      5.15.10         py310h6a678d5_0
pyqt5-sip                 12.13.0         py310h5eee18b_0
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.10.13         hd12c33a_1_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-tzdata             2023.4             pyhd8ed1ab_0    conda-forge
python_abi                3.10                    4_cp310    conda-forge
pytz                      2023.3.post1       pyhd8ed1ab_0    conda-forge
pyyaml                    6.0.1           py310h2372a71_1    conda-forge
qt-main                   5.15.2              h53bd1ea_10
rdma-core                 49.0                 hd3aeb46_2    conda-forge
re2                       2023.06.02           h2873b5e_0    conda-forge
readline                  8.2                  h8228510_1    conda-forge
s2n                       1.4.1                h06160fa_0    conda-forge
scipy                     1.11.4          py310hb13e2d6_0    conda-forge
seaborn                   0.13.1               hd8ed1ab_0    conda-forge
seaborn-base              0.13.1             pyhd8ed1ab_0    conda-forge
setuptools                69.0.3             pyhd8ed1ab_0    conda-forge
sip                       6.7.12          py310hc6cd4ac_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snappy                    1.1.10               h9fff704_0    conda-forge
sortedcontainers          2.4.0              pyhd8ed1ab_0    conda-forge
sqlite                    3.44.2               h2c6b66d_0    conda-forge
statsmodels               0.14.1          py310h1f7b6fc_0    conda-forge
tblib                     3.0.0              pyhd8ed1ab_0    conda-forge
tk                        8.6.13          noxft_h4845f30_101    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
toolz                     0.12.0             pyhd8ed1ab_0    conda-forge
tornado                   6.3.3           py310h2372a71_1    conda-forge
tzdata                    2023d                h0c530f3_0    conda-forge
ucx                       1.15.0               h75e419f_2    conda-forge
unicodedata2              15.1.0          py310h2372a71_0    conda-forge
urllib3                   2.1.0              pyhd8ed1ab_0    conda-forge
wget                      1.20.3               ha35d2d1_1    conda-forge
wheel                     0.42.0             pyhd8ed1ab_0    conda-forge
xkeyboard-config          2.40                 hd590300_0    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libx11               1.8.7                h8ee46fc_0    conda-forge
xorg-libxau               1.0.11               hd590300_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-xextproto            7.3.0             h0b41bf4_1003    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xyzservices               2023.10.1          pyhd8ed1ab_0    conda-forge
xz                        5.4.5                h5eee18b_0
yaml                      0.2.5                h7f98852_2    conda-forge
zict                      3.0.0              pyhd8ed1ab_0    conda-forge
zipp                      3.17.0             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               hd590300_5    conda-forge
zstd                      1.5.5                hfc55251_0    conda-forge
```

**Comment by hghezzi** [comment]
Hi again!

Apologies for the delay in my response, I was fixing and testing the code. The issue you encountered was due to a bug in the renaming of FASTA headers of Prokka-generated files, which led to downstream parsing errors. 

The new puppy version, v.1.0.2 (or source code in this repo), reflects these changes and should be able to handle Prokka files appropriately. Please let me know if it works or you encounter any new issues! :))

**Comment by cvtang** [comment]
The bug-fix worked!! 
Thank you so much for your help and for making my first github issue experience wonderful! <3
Will be in touch if any issues arise with the next step ;)
