### ISSUE TITLE
Potential KeyError at puppy-primers step?

### ISSUE THREAD

**Issue by haileighpatterson** [Tropini-lab/PUPpy#8]
Heya,

I am attempting to run PUPpy on a set of bacterial isolates and some reference genomes. I've installed PUPpy through conda and have successfully completed the puppy-align step, which gave the "Everything went smoothly" message. 

However, when I run the puppy-primers command on the ResultsDB.tsv output, I keep getting the following error: 

> Renaming FASTA headers (if needed)...
> 
> Loading the alignments file (/PATH/puppy_fastafiles/test/OUTPUT_puppy-align/ResultDB.tsv, size = 0.788806724 GB) as a Dask Dataframe...
> Converting Dask Dataframe to Pandas dataframe...
> Traceback (most recent call last):
>   File "/PATH/puppy_env/lib/python3.10/site-packages/pandas/core/indexes/range.py", line 414, in get_loc
>     return self._range.index(new_key)
> ValueError: 1 is not in range
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/PATH/puppy_env/bin/puppy-primers", line 577, in <module>
>     parse_alignments(ResultDB)
>   File "/PATH/puppy_env/bin/puppy-primers", line 466, in parse_alignments
>     dataframe.insert(loc=1, column="query_gene", value="cds_" + queryNames[1])
>   File "/PATH/puppy_env/lib/python3.10/site-packages/pandas/core/frame.py", line 3893, in __getitem__
>     indexer = self.columns.get_loc(key)
>   File "/PATH/puppy_env/lib/python3.10/site-packages/pandas/core/indexes/range.py", line 416, in get_loc
>     raise KeyError(key) from err
> KeyError: 1

Any help appreciated, I am reasonably new to this process so apologies if it is something obvious. 

Cheers

**Comment by hghezzi** [comment]
Hi!

Thank you for bringing up this issue! Based on the traceback it seems like an older version of PUPpy is being used, which may explain the issue. Could you please check the package version by running the commands below?

`conda activate puppy` to activate the puppy conda environment
`conda list puppy` to check the puppy package version

As of today, you should see PUPpy version 1.0.2. Is that the case? If not, please update the package by running:

`conda update puppy` Or by installing again from scratch.

Please let me know if the above was not the problem or if this fixed it!

**Comment by haileighpatterson** [comment]
Hi thanks for your reply. 

I just updated using your suggested method to 1.0.2. Unfortunately when I ran the script again, I got the same error. 

Thanks

**Comment by hghezzi** [comment]
Ah, sorry about that! Could you provide a bit more information about the input files and commands you used so that I can try to replicate your error?

For your input files, could you include examples of filenames, FASTA headers and/or NCBI accession numbers so that I can try using some of these specific files?

For the code, can you write the specific puppy-align and puppy-primers scripts you ran?

In the meantime, could you check if the puppy-align output file "ResultDB.tsv" has "query" as the first column and could you paste here a handful of rows for this column?

Thanks!!

**Comment by haileighpatterson** [comment]
Hi again, 

Please see below slurm script used to run everything: 

```
#!/bin/bash -e

#SBATCH --account           uoa03687
#SBATCH --job-name          puppy
#SBATCH --mem               20G   
#SBATCH --cpus-per-task     16
#SBATCH --time              24:00:00
#SBATCH --output            slurmout.%j.out
#SBATCH --mail-type         ALL
#SBATCH --mail-user         haileigh.patterson@plantandfood.co.nz

##already created environment previously

module purge && module load Miniconda3
source $(conda info --base)/etc/profile.d/conda.sh
export PYTHONNOUSERSITE=1

conda activate /nesi/nobackup/uoa03687/Haileigh_Patterson/puppy_env

cd /nesi/nobackup/uoa03687/Haileigh_Patterson/puppy_fastafiles

puppy-align -pr /nesi/nobackup/uoa03687/Haileigh_Patterson/puppy_fastafiles/test/INPUT_primerTarget -nt /nesi/nobackup/uoa03687/Haileigh_Patterson/puppy_fastafiles/test/INPUT_nonTarget -o /nesi/nobackup/uoa03687/Haileigh_Patterson/puppy_fastafiles/test/OUTPUT_puppy-align

puppy-primers -pr /nesi/nobackup/uoa03687/Haileigh_Patterson/puppy_fastafiles/test/INPUT_primerTarget -i /nesi/nobackup/uoa03687/Haileigh_Patterson/puppy_fastafiles/test/OUTPUT_puppy-align/ResultDB.tsv -o /nesi/nobackup/uoa03687/Haileigh_Patterson/puppy_fastafiles/test/OUTPUT_puppy-primers_unique

conda deactivate 
```

And an example of the a header of one of my .fna files (renamed from prokka .ffn format). All input files have _cds.fna at the end as is required.

![image](https://github.com/Tropini-lab/PUPpy/assets/100541802/5ced4436-80ec-4e16-b104-50bd858a21bf)

And this is the head of my ResultDB.tsv table: 

![image](https://github.com/Tropini-lab/PUPpy/assets/100541802/2c2ee7b9-7af3-40f8-b97a-ce1073abb089)

Cheers

**Comment by hghezzi** [comment]
Hi again!

Before you try the next troubleshooting step, could you please update to the latest version (v1.0.3)? It shouldn't matter in this specific case but I made a few changes to the scripts.

Thank you so much for providing the screenshots. I noticed that your FASTA headers and "query" rows both have unexpected extensions in the names (i.e. .fa and .fasta). A key feature of PUPpy involves renaming FASTA headers based on the filenames, which is a permanent change to those files. This means that the first time you run either `puppy-align` or `puppy-primers` your input CDS files are modified based on the current filenames (and won't be modified again in future scripts executions). If you had originally run those same input files with an outdated puppy version or with an incorrect filename, it is possible that your input files now have incorrect FASTA headers and won't work even if the scripts are fixed. 

Could you try starting with fresh (i.e. from the source) input files that have not been modified and running puppy again? I also recommend duplicating your CDS input folder so that you always have a copy of your raw input files.

Please let me know if this fixes it or if more troubleshooting is needed :))

**Comment by haileighpatterson** [comment]
Hiya, 

Updated again successfully. 

I have tried again with completely fresh files and unfortunately had the same issue, although it seemed to run for a lot longer at the align stage than it had previously. 

I tried to attach a couple sequences however file type wasn't supported - would greatly appreciate if you could see if they work on your end if you have time I can email them to you. Really appreciate all your help thus far. 

Cheers

**Comment by hghezzi** [comment]
Hi again!

Yes, please feel free to email me so that I can do a bit of troubleshooting on my end and look further into this!

**Comment by haileighpatterson** [comment]
I couldn't find your email publicly, would you mind reaching out haileigh.patterson <at> plantandfood.co.nz
